name: Lifecheck

on:
    schedule:
        - cron: '0 * * * *'

jobs:
    lifecheck:
        runs-on: ubuntu-latest

        steps:
            - name: Check if app is active
              run: |
                response=$(curl --write-out '%{http_code}' --silent --output /dev/null new.babel-revolution.fr)
                if [ "$response" -ne 200 ]; then
                    echo "App is not active"
                    exit 1
                else
                    echo "App is active"
                fi