name: Notify Discord on Staging Push

on:
    push:
        branches:
            - staging

jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Get commit messages
              id: commits
              run: |
                  commits=$(git log origin/staging --pretty=format:'%h - %s (%an)' --abbrev-commit)
                  echo "messages=${commits}" >> $GITHUB_OUTPUT

            - name: Notify on Discord Webhook
              env:
                  BABEL_DISCORD_WEBHOOK_URL: ${{ secrets.BABEL_DISCORD_WEBHOOK_URL }}
              run: |
                  curl -X POST -H 'Content-type: application/json' --data "{\"embeds\": [{\"title\": \"New commits pushed to staging branch\", \"description\": \"${{ env.messages }}\", \"color\": 5814783}]}" $BABEL_DISCORD_WEBHOOK_URL
